### ISSUE TITLE
What does it mean by "This module is only meant for NXP-based kernel up to 4.1.x" ?

### ISSUE THREAD

**Issue by l4es** [Freescale/kernel-module-imx-gpu-viv#14]
Hi,
I'm using Linux kernel version 4.9.144 which is based on [toradex_4.9-2.3.x-imx](https://git.toradex.com/cgit/linux-toradex.git/log/?h=toradex_4.9-2.3.x-imx)  and with this module "kernel-module-imx-gpu-viv" activated within Buildroot,  the **galcore** module is automatically disabled from the kernel's menuconfig (which is enabled by default) and it is not compiled nor generated.

Also I saw that "**_This module is only meant for NXP-based kernel up to 4.1.x._**" , I'd like to know how would I get the galcore compiled for the kernel version : 4.9.144, please ?

Moreover, from this link https://boundarydevices.com/customizing-ubuntudebian-kernels/, it is said that for kernel version is 4.1.15 or higher, galcore module has to be built externally and independently to the kernel. Could you confirm, please ?

Best regards,
Khang

**Comment by l4es** [comment]
Hi again,

I could finally get the **galcore** compiled which is located in **_/lib/modules/4.9.144/extra/_** on target system (This is done under Buildroot by activating BR2_PACKAGE_GSTREAMER & BR2_PACKAGE_GST_FSL_PLUGINS in order to properly activate BR2_PACKAGE_FREESCALE_IMX). During the compilation, some imx libraries are copied from  https://source.codeaurora.org/external/imx/imx-lib as well. 

However, I struggled with following error during module probing :

> root@imx-buildroot:~# modprobe galcore  
[  142.448547] galcore: loading out-of-tree module taints kernel.    
[  142.480854] Galcore version 6.2.4.150331    
[  142.498241] galcore: probe of 130000.gpu failed with error -22

I'd like to know if the newer-than-4.1.x kernel version is the main problem?

Thank in advance,
Khang

**Comment by otavio** [comment]
I don't know how buildroot is doing this integration, so please check if it is something needing rework there.

At Yocto Project, it builds and runs on multiple NXP-based Linux kernel forks.

**Comment by l4es** [comment]
Hi again,  
I went back to buildroot-2017.08 and was able have galcore sucessfully loaded within kernel 4.1.x. I think that there's some thing different btw the kernels' versions. I will investigate this later and I think this ticket can be closed.

Regards,
Pascal
