### ISSUE TITLE
File descriptor leak on imx-gpu-viv drivers

### ISSUE THREAD

**Issue by vodkapomme** [Freescale/kernel-module-imx-gpu-viv#16]
Hello,

I'm facing this issue with wpe-webkit https://github.com/Igalia/cog/issues/87
I'm building for i.MX 8MQuad using thud branch, the fdo backend and the core-image-weston image

Is this an imx-gpu-viv issue ?

**Comment by otavio** [comment]
@vodkapomme can you cook a fix for it?

**Comment by asabil** [comment]
Any update regarding this?

**Comment by angolini** [comment]
It looks like we had no update in 2 years.

Would it be possible to be tested again using master? What is the current status of this issue?

**Comment by vodkapomme** [comment]
Hello, 
As we were unable to find a clever solution and create a patch for this issue, we have chosen to go with another soc.
Unfortunately i haven't got a working target board for imx8mq around me and so i won't be able to test against master.
I think we can close my issue but maybe there still are people looking a proper workaround.
