### ISSUE TITLE
panic in gckKERNEL_CreateProcessDB

### ISSUE THREAD

**Issue by pavelp84** [Freescale/kernel-module-imx-gpu-viv#24]
Hello!

It's need to remove database from hash after gckKERNEL_DeinitDatabase()
call in gckKERNEL_CreateProcessDB(). In other case it could be found in
hash after another call of gckKERNEL_CreateProcessDB() and the kernel
will go to panic() while gckOS_AtomIncrement() call.

This bug was found with sress-ng test:
./stress-ng --dev-file /dev/galcore --dev 0

Patch:
Index: drivers/mcst/gpu-viv/hal/kernel/gc_hal_kernel_db.c
===================================================================
--- drivers/mcst/gpu-viv/hal/kernel/gc_hal_kernel_db.c  (revision 27106)
+++ drivers/mcst/gpu-viv/hal/kernel/gc_hal_kernel_db.c  (working copy)
@@ -520,6 +520,39 @@
     return status;
 }
 
+static void gckKERNEL_RemoveFromHash(
+    IN gckKERNEL Kernel,
+    IN gctSIZE_T slot,
+    IN gcsDATABASE_PTR database
+)
+{
+    gcsDATABASE_PTR db = gcvNULL, prev = gcvNULL;
+
+    /* Walk the hash list. */
+    for (db = Kernel->db->db[slot];
+         db != gcvNULL;
+         db = db->next)
+    {
+        if (db->processID == database->processID)
+        {
+            break;
+        }
+        prev = db;
+    }
+
+    /* Remove the database from the hash list. */
+    if (prev)
+    {
+        prev->next = database->next;
+    }
+    else
+    {
+        Kernel->db->db[slot] = database->next;
+    }
+}
+
 /*******************************************************************************
 ***** Public API **************************************************************/
 
@@ -670,6 +703,10 @@
     {
         gcmkVERIFY_OK(gckKERNEL_DeinitDatabase(Kernel, database));
 
+        gckKERNEL_RemoveFromHash(Kernel, slot, database);
+
         if (pointer)
         {
             gcmkOS_SAFE_FREE(Kernel->os, pointer);

**Comment by otavio** [comment]
Please fork this repo and prepare a PR.

**Comment by angolini** [comment]
What is the status of this issue?

I'm closing it, but if there is any update, please reopen the issue with latest info (or the link to PR)
