### ISSUE TITLE
Non-reproducable build on new release

### ISSUE THREAD

**Issue by otavio** [Freescale/kernel-module-imx-gpu-viv#26]
The following code needs rework:
https://github.com/gibsson/kernel-module-imx-gpu-viv/blob/20595cdfe4b12a5bb3f3a5b53f866b7bc504d53f/kernel-module-imx-gpu-viv-src/hal/os/linux/kernel/platform/freescale/gc_hal_kernel_platform_imx.config#L30-L34

**Comment by otavio** [comment]
@gibsson can you take a look at it?

**Comment by gibsson** [comment]
What about removing that config change in master branch? The code already supports not to have GALCORE_BUILD_BY defined.

**Comment by otavio** [comment]
It is fine with me. I see no value in adding it.
