### ISSUE TITLE
Source of NPU Part

### ISSUE THREAD

**Issue by tizbac** [Freescale/kernel-module-imx-gpu-viv#38]
Hello, is it possible to have source code with NPU? Some vivante gpu implementations like the one in RK1808 does have NPU

**Comment by gibsson** [comment]
This driver already includes the NPU parts.

**Comment by tizbac** [comment]
Let me explain better i was looking at being able to recompile galcore.ko for RK1808, on the source code of current master i can't find any references to NPU and to many of the dmesg lines RK1808 prints when loading that galcore.ko
For example  
   20.846644] galcore: loading out-of-tree module taints kernel.
[   20.849220] galcore: npu init.
[   20.851293] galcore: start npu probe.
[   20.851624] npu: platform_get_irq irq = 30
[   20.851799] npu: platform_get_resource registerMemBase = ffbc0000, registerMemSize = 1000
[   20.851817] Galcore version 6.4.3.5.293908
.....
[   20.864052] galcore ffbc0000.npu: Init npu devfreq
[   20.864255] galcore ffbc0000.npu: leakage=32
[   20.864403] galcore ffbc0000.npu: pvtm-volt-sel=2
[   20.865465] galcore ffbc0000.npu: avs=0
[   20.867768] galcore ffbc0000.npu: l=0 h=2147483647 hyst=5000 l_limit=0 h_limit=0

**Comment by gibsson** [comment]
You need to ask the Silicon Vendor of that SoC then.
The i.MX 8M Plus processor does have a Verisilicon NPU and uses the source code from this repo with no modification.
Each galcore driver has a vendor-specific file, you need to get the one from Rockchip.
https://github.com/Freescale/kernel-module-imx-gpu-viv/blob/master/kernel-module-imx-gpu-viv-src/hal/os/linux/kernel/platform/freescale/gc_hal_kernel_platform_imx.c
