### ISSUE TITLE
Makefile:6: recipe for target 'all' failed

### ISSUE THREAD

**Issue by ghost** [Freescale/kernel-module-imx-gpu-viv#5]
Hello,

I'm trying to build it and having this build issue:

> ubuntu@imx6qp:~/gpu_pack/kernel-module-imx-gpu-viv$ make
> make -C  M=/home/ubuntu/gpu_pack/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src AQROOT=/home/ubuntu/gpu_pack/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src
> make[1]: *** M=/home/ubuntu/gpu_pack/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src: No such file or directory.  Stop.
> Makefile:6: recipe for target 'all' failed
> make: *** [all] Error 2
> 

Does _KERNEL_SRC_ needs to be defined before?

**Comment by suvirbhargav** [comment]
Yup, fails for me too.

```
make all
make -C  M=/home/debian/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src AQROOT=/home/debian/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src
make[1]: *** M=/home/debian/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src: No such file or directory.  Stop.
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
root@nitrogen:/home/debian/kernel-module-imx-gpu-viv# 
root@nitrogen:/home/debian/kernel-module-imx-gpu-viv# 
root@nitrogen:/home/debian/kernel-module-imx-gpu-viv# 
root@nitrogen:/home/debian/kernel-module-imx-gpu-viv# 
root@nitrogen:/home/debian/kernel-module-imx-gpu-viv# ls -l
total 28
-rw-r--r-- 1 root root 18006 Mar  8 06:47 COPYING
-rw-r--r-- 1 root root   523 Mar  8 06:47 Makefile
drwxr-xr-x 3 root root  4096 Mar  8 06:47 kernel-module-imx-gpu-viv-src
```

Kernel 3.14.38

**Comment by otavio** [comment]
This is working fine for Yocto Project.

The recipe which does the build can be seen at:

https://github.com/Freescale/meta-freescale/blob/master/recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_5.0.11.p8.6%2Bfslc.bb

**Comment by suvirbhargav** [comment]
ah ok. i was compiling it on device itself with normal make. Not on yocto setup.
Is it possible to have in setup for ubuntu/debian configure, make style?

**Comment by otavio** [comment]
The way it is supported is using the kernel source for external module building. It is possible, sure, to build but you need the running kernel headers and build scripts installed.

**Comment by rameshchandrakasan** [comment]
Dear Otavio
I am also getting same Error.
Pls suggest

ramesh@ramesh-16:~/imx6develop/ubuntize/kernel-module-imx-gpu-viv$ make
make -C /home/ramesh/imx6develop/ubuntize/linux-imx6 M=/home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src AQROOT=/home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src
make[1]: Entering directory '/home/ramesh/imx6develop/ubuntize/linux-imx6'
  CC [M]  /home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src/hal/os/linux/kernel/gc_hal_kernel_device.o
cc1: error: -Werror=misleading-indentation: no option -Wmisleading-indentation
scripts/Makefile.build:258: recipe for target '/home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src/hal/os/linux/kernel/gc_hal_kernel_device.o' failed
make[2]: *** [/home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src/hal/os/linux/kernel/gc_hal_kernel_device.o] Error 1
Makefile:1385: recipe for target '_module_/home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src' failed
make[1]: *** [_module_/home/ramesh/imx6develop/ubuntize/kernel-module-imx-gpu-viv/kernel-module-imx-gpu-viv-src] Error 2
make[1]: Leaving directory '/home/ramesh/imx6develop/ubuntize/linux-imx6'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by otavio** [comment]
You must use:

```
unset LDFLAGS
unset CFLAGS
```

**Comment by rameshchandrakasan** [comment]
Dear otavio,

Thanks a lot & lot
It works!!!
**Regards**
Ramesh

**Comment by nikitachrs** [comment]
Dear Otavio!
Is config for Xorg.conf change for 6.2.2 version? I use old config for 5.0.11 and xinit is not started. Libs are update.
Where I can find xorg.config or tutorial for new version?

**Comment by otavio** [comment]
Oh, this is not related to this issue, I don't use such old X for long time ... sorry.
