### ISSUE TITLE
Usage of kernel-module-imx-gpu-viv with 3.14.79 vanilla kernel

### ISSUE THREAD

**Issue by alihoumani** [Freescale/kernel-module-imx-gpu-viv#7]
Hi,

While trying to compile kernel-module-imx-gpu-viv with  3.14.79 vanilla kernel I am getting an error of missing header files busfreq.imx.h. Is there any other alternative to load the drivers with  3.14.79 vanilla kernel? Or I need to redo all the patches done by freescale?

/A

**Comment by otavio** [comment]
With mainline kernel you will need to do some patching. You can use the 3.14 branch which has most of stable releases merged if you want.

**Comment by alihoumani** [comment]
You mean the Freescale imx 3.14 branch?

**Comment by otavio** [comment]
Yes.
